from app.modules.registry import API_ROUTERS


def test_api_router_registry_exposes_expected_prefixes():
    assert [router.prefix for router in API_ROUTERS] == [
        "/auth",
        "/health",
        "/api/master",
        "/api/tasks",
        "/api/task-history",
        "/person",
        "/customer",
        "/companydepartment",
        "/permissions",
        "/workflows",
        "/technologies",
        "/yt_file",
        "/yt_timesheet",
        "/yt_log",
        "/warehouse",
        "/productcatalog",
        "/yt_report",
        "/quality",
        "/api/transfer-area",
        "/manufactureplan",
        "/report",
        "/device",
        "/material",
        "/api/storage",
        "/yt_barcode",
        "/yt_object",
        "/api/attendance",
        "/api/system",
        "/api/terminal-control",
        "/api/mq",
        "/api/laboratory",
    ]
