import { SAMPLE_FLOW_STEPS } from "@/modules/samples/samplesFlowModel";
import {
  STATUS_COMPLETED,
  STATUS_RETENTION,
  STATUS_RUNNING,
  STATUS_SCHEDULED,
  STATUS_WAITING,
} from "@/modules/tasks/model";

const SALT_SPRAY_LAB = "盐雾试验室";
const LAB_COMPARE_STATUS = "已到达实验室";
const LAB_INSTALL_STATUS = "工装夹具安装";
const LAB_READY_STATUS = "实验准备就绪";
const LAB_RESET_STATUS = "送至实验室";
const EXPERIMENT_COMPLETED_STATUS = "实验已完成";
const PRE_DISPATCH_STAGING_LOCATION = "恒温恒湿间（暂存间）";
const PRE_DISPATCH_STAGING_STATUS = "已到达暂存间";
const APPEARANCE_INSPECTION_LOCATION = "外观检测间";
const APPEARANCE_INSPECTION_STOCKED_STATUS = "实验后外观检测间存放";
const PRE_EXPERIMENT_APPEARANCE_STOCKED_STATUS = "实验前外观检测间存放";
const UNIFIED_TRAY_FLOW_STATUS_RANK = new Map(SAMPLE_FLOW_STEPS.map((step, index) => [step.label, index]));
const PRE_DISPATCH_STATUSES = new Set(["到货", "已接收", "送至暂存间", "已到达暂存间"]);
const AXIS_PARTIAL_REAL_FOLLOW_UP_STATUSES = new Set([
  LAB_RESET_STATUS,
  LAB_COMPARE_STATUS,
  LAB_INSTALL_STATUS,
  LAB_READY_STATUS,
  "放置暂存间",
  PRE_DISPATCH_STAGING_STATUS,
  APPEARANCE_INSPECTION_STOCKED_STATUS,
]);
const APPEARANCE_STORAGE_STATUSES = new Set([
  APPEARANCE_INSPECTION_STOCKED_STATUS,
  PRE_EXPERIMENT_APPEARANCE_STOCKED_STATUS,
]);
const RUNNING_EXPERIMENT_STATUSES = new Set(["实验进行中", "实验中"]);
const LAB_DISPATCH_HISTORY_ACTIONS = new Set(["暂存间扫码出库", "外观检测间扫码出库", "接驳区扫码出库", "送至实验室"]);
const LABORATORY_TASK_FLOW_STEPS = [
  { key: "waiting", label: STATUS_WAITING },
  { key: "scheduled", label: STATUS_SCHEDULED },
  { key: "running", label: STATUS_RUNNING },
  { key: "completed", label: STATUS_COMPLETED },
  { key: "returned", label: STATUS_RETENTION },
];
const LABORATORY_TASK_FLOW_INDEX = new Map(LABORATORY_TASK_FLOW_STEPS.map((step, index) => [step.label, index]));

export {
  APPEARANCE_INSPECTION_LOCATION,
  APPEARANCE_INSPECTION_STOCKED_STATUS,
  APPEARANCE_STORAGE_STATUSES,
  AXIS_PARTIAL_REAL_FOLLOW_UP_STATUSES,
  EXPERIMENT_COMPLETED_STATUS,
  LABORATORY_TASK_FLOW_INDEX,
  LABORATORY_TASK_FLOW_STEPS,
  LAB_COMPARE_STATUS,
  LAB_DISPATCH_HISTORY_ACTIONS,
  LAB_INSTALL_STATUS,
  LAB_READY_STATUS,
  LAB_RESET_STATUS,
  PRE_DISPATCH_STATUSES,
  PRE_DISPATCH_STAGING_LOCATION,
  PRE_DISPATCH_STAGING_STATUS,
  PRE_EXPERIMENT_APPEARANCE_STOCKED_STATUS,
  RUNNING_EXPERIMENT_STATUSES,
  SALT_SPRAY_LAB,
  UNIFIED_TRAY_FLOW_STATUS_RANK,
};
